// <auto-generated />
using System;
using BitOfTech.Expenses.Mcp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitOfTech.Expenses.Mcp.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20260922210315_AddApprovalAndEntraObjectId")]
    partial class AddApprovalAndEntraObjectId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitOfTech.Expenses.Mcp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasFilter("[EntraObjectId] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sara.haddad@bitoftech.net",
                            Name = "Sara Haddad"
                        },
                        new
                        {
                            Id = 2,
                            Email = "omar.nasser@bitoftech.net",
                            Name = "Omar Nasser"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lina.farah@bitoftech.net",
                            Name = "Lina Farah"
                        },
                        new
                        {
                            Id = 4,
                            Email = "taiseer.joudeh@bitoftech.net",
                            Name = "Taiseer Joudeh"
                        });
                });

            modelBuilder.Entity("BitOfTech.Expenses.Mcp.Models.ExpenseLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ExpenseReportId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("IncurredOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseReportId");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 410.00m,
                            Category = "Travel",
                            Description = "Return flight LHR to BER",
                            ExpenseReportId = 1001,
                            IncurredOn = new DateOnly(2026, 8, 31)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 312.50m,
                            Category = "Accommodation",
                            Description = "Hotel, two nights",
                            ExpenseReportId = 1001,
                            IncurredOn = new DateOnly(2026, 8, 31)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 120.00m,
                            Category = "Travel",
                            Description = "Airport transfers",
                            ExpenseReportId = 1001,
                            IncurredOn = new DateOnly(2026, 9, 1)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 165.00m,
                            Category = "Training",
                            Description = "AZ-204 exam voucher",
                            ExpenseReportId = 1002,
                            IncurredOn = new DateOnly(2026, 8, 12)
                        },
                        new
                        {
                            Id = 5,
                            Amount = 96.75m,
                            Category = "Travel",
                            Description = "Train tickets",
                            ExpenseReportId = 1003,
                            IncurredOn = new DateOnly(2026, 9, 7)
                        },
                        new
                        {
                            Id = 6,
                            Amount = 689.00m,
                            Category = "Accommodation",
                            Description = "Hotel, three nights",
                            ExpenseReportId = 1003,
                            IncurredOn = new DateOnly(2026, 9, 7)
                        },
                        new
                        {
                            Id = 7,
                            Amount = 420.00m,
                            Category = "Meals",
                            Description = "Team meals",
                            ExpenseReportId = 1003,
                            IncurredOn = new DateOnly(2026, 9, 8)
                        },
                        new
                        {
                            Id = 8,
                            Amount = 48.40m,
                            Category = "Communications",
                            Description = "Mobile plan",
                            ExpenseReportId = 1004,
                            IncurredOn = new DateOnly(2026, 8, 25)
                        },
                        new
                        {
                            Id = 9,
                            Amount = 40.00m,
                            Category = "Communications",
                            Description = "Home broadband",
                            ExpenseReportId = 1004,
                            IncurredOn = new DateOnly(2026, 8, 25)
                        },
                        new
                        {
                            Id = 10,
                            Amount = 210.00m,
                            Category = "Meals",
                            Description = "Dinner for four",
                            ExpenseReportId = 1005,
                            IncurredOn = new DateOnly(2026, 9, 15)
                        });
                });

            modelBuilder.Entity("BitOfTech.Expenses.Mcp.Models.ExpenseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ApprovedOn")
                        .HasColumnType("date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("SubmittedOn")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Status");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Currency = "EUR",
                            EmployeeId = 1,
                            Status = "Submitted",
                            SubmittedOn = new DateOnly(2026, 9, 2),
                            Title = "Berlin customer workshop",
                            TotalAmount = 842.50m
                        },
                        new
                        {
                            Id = 1002,
                            Currency = "USD",
                            EmployeeId = 1,
                            Status = "Approved",
                            SubmittedOn = new DateOnly(2026, 8, 14),
                            Title = "Azure certification exam",
                            TotalAmount = 165.00m
                        },
                        new
                        {
                            Id = 1003,
                            Currency = "GBP",
                            EmployeeId = 2,
                            Status = "Submitted",
                            SubmittedOn = new DateOnly(2026, 9, 9),
                            Title = "London team offsite",
                            TotalAmount = 1205.75m
                        },
                        new
                        {
                            Id = 1004,
                            Currency = "GBP",
                            EmployeeId = 3,
                            Status = "Rejected",
                            SubmittedOn = new DateOnly(2026, 8, 28),
                            Title = "Mobile and broadband, August",
                            TotalAmount = 88.40m
                        },
                        new
                        {
                            Id = 1005,
                            Currency = "EUR",
                            EmployeeId = 2,
                            Status = "Draft",
                            Title = "Client dinner, Amsterdam",
                            TotalAmount = 210.00m
                        });
                });

            modelBuilder.Entity("BitOfTech.Expenses.Mcp.Models.ExpenseLine", b =>
                {
                    b.HasOne("BitOfTech.Expenses.Mcp.Models.ExpenseReport", null)
                        .WithMany("Lines")
                        .HasForeignKey("ExpenseReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BitOfTech.Expenses.Mcp.Models.ExpenseReport", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
